### ISSUE TITLE
API deprecated 

### ISSUE THREAD

**Issue by friimaind** [DashMedia/PurgeCloudFlare#3]
Hi!
CloudFlare is removing support for the API used on this component so it will be great to upgrade it.

> CloudFlare is removing support for this API on November 9th, 2016. Please use CloudFlare’s API v4 instead. Documentation is available at api.cloudflare.com

Here are the details: https://www.cloudflare.com/docs/client-api.html

EDIT: I made a quick fork here https://github.com/friimaind/PurgeCloudFlareV4

**Comment by JayCarney** [comment]
Thanks for the heads up, I'll get a chance to have a look over your fork in the next couple days and see what we can do about releasing a new version.

**Comment by JayCarney** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test](https://trello.com/c/Hj4x118Z/2-test)
