### ISSUE TITLE
Cache not clearing

### ISSUE THREAD

**Issue by getandyjones** [DashMedia/PurgeCloudFlare#4]
Hi,

Since installing this plugin, I find that If I try and save a resource, or clear the cache, the progrss bar comes up but doesn't complete.
I have entered my API key and email address in system settings.
Any ideas what else this could be?

**Comment by JayCarney** [comment]
Are you getting any errors in console?

Try checking the JSON response for the calls to any .php files once you've clicked save or clear, looking for one that doesn't say success, if the response itself doesn't contain any useful info, the headers sent with the request can help narrow down where the problem is occurring.

**Comment by getandyjones** [comment]
Hi - Thanks for getting back to me.
I'm not getting any errors in console. 
I'm not sure how to check the JSON calls to php files unfortunately. Any tips on how to do this?
I have reinstalled the Extra just in case it's that but it's not.

**Comment by JayCarney** [comment]
To see if I can replicate the issue on my end, what version versions of MODX and PHP are you running? (you can jump into the `manage->reports->system info->phpinfo()` section of MODX to get your PHP version if you're not sure)

### In terms of checking JSON calls

- Open web inspector before saving or clearing the cache
- Go to the network tab
- Click save or clear cache
- Go through the index.php requests, and check the 'response' section
- If one of these contains a response with an error, or something that isn't a JSON success string
  - Right click on the request in the network tab and choose save a HAR

You can add the HAR file as an attachment to a reply, or copy and paste the whole thing in, it's just a JSON file with the details of the network request

**Comment by getandyjones** [comment]
Hi There,

Thank you for this - you're very helpful.

*See below the spec:*
MODX Revolution 2.5.4-pl (traditional)
PHP Version 5.3.28

I checked the inspector when clearing the cache, and it creates line upon
line when trying to clear the cache - each on the same, as if it's caught
in a loop?
When I checked the 'response' section - it was totally empty - I checked
every line.

I saved one of them as a HAR file, but not sure f this is any use?

Thanks again for your help on this!



------------------------------
[image: tyga]
Andy Jones
Creative Director
TYGA Marketing Limited
TYGA House, 13 Alban Park, Hatfield Road, St. Albans, Herts, AL4 0JJ

01727 898 191 <00441727898191>   www.tyga.co.uk
<https://twitter.com/tygamarketing>
<https://www.facebook.com/tygamarketing/>
<https://www.youtube.com/channel/UCIa2YVBEgBjutTg79e3yX3A>
------------------------------

**Comment by JayCarney** [comment]
Ahh, found it.

It's a bug with php 5.3.x not supporting array shorthand.

New version of the extra is in MODX Extras repo, thanks for the info you provided, it really helped in tracking down the error.

**Comment by getandyjones** [comment]
Perfect - it works!
Thanks so much for looking into this.
This is why I love MODX and the community around it!!

Andy


------------------------------
[image: tyga]
Andy Jones
Creative Director
TYGA Marketing Limited
TYGA House, 13 Alban Park, Hatfield Road, St. Albans, Herts, AL4 0JJ

01727 898 191 <00441727898191>   www.tyga.co.uk
<https://twitter.com/tygamarketing>
<https://www.facebook.com/tygamarketing/>
<https://www.youtube.com/channel/UCIa2YVBEgBjutTg79e3yX3A>
------------------------------
